apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${GF_INFLUX_URL}
    isDefault: true
    jsonData:
      organization: ${GF_INFLUX_ORG}
      defaultBucket: ${GF_INFLUX_BUCKET}
      version: Flux
    secureJsonData:
      token: ${GF_INFLUX_TOKEN}
